### PR TITLE
Tested on 1.10.1 -> Changed it quite a bit

### PR DESCRIPTION
**Pull request by clonemeagain**
Added translation support, added more info, expanded README.. added pictures/screenshots and instructions on how to configure in Slack. 

Added some validation and error logging, incorporated the formatting rules they stipulate.

### CODE REVIEW

**Review by jeffnewbold — APPROVED** [review]

**Review by jeffnewbold — CHANGES_REQUESTED** [review]
the date/time is off for me on this. It is around ...5 hours behind the actual time?

**Comment by jeffnewbold** [comment]
Another question - is it possible to add the body/topic of the request? IE %{ticket.thread.original}

**Comment by clonemeagain** [comment]
Hiya, I'm thinking the timestamp function from osTicket core isn't relevant here, needs to be changed to just `time()`.

Hmm, interesting idea. Could build the post text from variables, so you can add whatever you want etc.. could be good! I'll test it and update

**Comment by jeffnewbold** [comment]
I would love to help if you post. Thank you for this Aaron btw!


On Thu, Nov 9, 2017, at 07:24 AM, Aaron wrote:
> Hiya, I'm thinking the timestamp function from osTicket core isn't
> relevant here, needs to be changed to just time().> Hmm, interesting idea. Could build the post text from variables,
> so you can add whatever you want etc.. could be good! I'll test it
> and update> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/thammanna/osticket-slack/pull/11#issuecomment-343153236

**Comment by clonemeagain** [comment]
@jeffnewbold  I got it working.

The template part is cool  because you can add your own Slack formatting: https://get.slack.help/hc/en-us/articles/202288908-how-can-i-add-formatting-to-my-messages- then use osTicket variables to define what the text says. 

I'm thinking I can delete half the crap I added now. Nice!
One issue, there is no way to filter invalid slack characters.. as I assume the template will include them (for links/formatting etc), however we can't then filter the message from the user to ensure it's not going to break. . . 
However, we can add arbitrary variables at that point, meaning, we can use something else to indicate the message text then just run it through the filter function first. Noice. 

This is now the default template: 
```
%{ticket.name.full} (%{ticket.email}) in *%{ticket.dept}* - _%{ticket.topic}_

```%{slack_safe_message}```
```

**Comment by jeffnewbold** [comment]
@clonemeagain (Aaron) -- haven't tracked the 'why' down yet, but randomly every 3rd or 4th day will get the following and it won't post the notification to the new ticket. I thought it was attachments / images, but this last one didn't have that.

Error sending to: https://hooks.slack.com/services/T7VP4****/B7UJH****/Ov9wYE**** Http code: 400 curl-error: 0

clicking the URL above gives me the message: invalid_payload

**Comment by clonemeagain** [comment]
@jeffnewbold had my fork de-tined, so issues can be raised against it directly now.

invalid_payload - the data sent in your request cannot be understood as presented; verify your content body matches your content type and is structurally valid.

Oh damn, maybe it was tweaked too much! (Mad with power?). I'll check it out.

**Comment by clonemeagain** [comment]
Have yet to see that in my testing. Could be utf8 related.. or the control chars, can you send me an example of one that fails?  I thought I followed their rules with regards to characters correctly!

**Comment by jeffnewbold** [comment]
Yes, will send one today. Do I add it here? (haven't sent anything via
Github before).

On Tue, Jan 2, 2018, at 11:32 PM, Aaron wrote:
> Have yet to see that in my testing. Could be utf8 related.. or the
> control chars, can you send me an example of one that fails?  I
> thought I followed their rules with regards to characters correctly!> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/thammanna/osticket-slack/pull/11#issuecomment-354940143

**Comment by clonemeagain** [comment]
Email is good mate: clonemeagain@gmail.com

**Comment by clonemeagain** [comment]
Hmm, rechecked the 400 error, and it is either a payload or user not found error, either way, we could be simplifying the payload and trying again, people might rely on slack for notifications and would otherwise miss a ticket etc.

On 400: simplify and resend, link and subject should be enough for an alert if there's an issue.
On 403: send admin alert, Permissions error, unable to post
On 410: send admin alert,  channel archived error, unable to post
On 500: server error at slack, simplify, add to message queue and resend whenever cron runs again..

https://api.slack.com/changelog/2016-05-17-changes-to-errors-for-incoming-webhooks

Actually, a message queue in the background would be a lot more responsive. Waiting for slack to post before returning the page adds a second or two when posting interactively (not an issue with email). Would help with busy sites processing a large volume of tickets. 
Would also make it easier for multiple channels.

**Comment by jeffnewbold** [comment]
That sounds good to me :)


On Mon, Jan 8, 2018, at 2:29 PM, Aaron wrote:
> Hmm, rechecked the 400 error, and it is either a payload or user not
> found error, either way, we could be simplifying the payload and
> trying again, people might rely on slack for notifications and would
> otherwise miss a ticket etc.> On 400: simplify and resend, link and subject should be enough for an
> alert if there's an issue.>  On 403: send admin alert, Permissions error, unable to post
>  On 410: send admin alert,  channel archived error, unable to post
>  On 500: server error at slack, simplify, add to message queue and
>  resend whenever cron runs again..> https://api.slack.com/changelog/2016-05-17-changes-to-errors-for-incoming-webhooks> Actually, a message queue in the background would be a lot more
> responsive. Waiting for slack to post before returning the page adds a
> second or two when posting interactively (not an issue with email).
> Would help with busy sites processing a large volume of tickets.>  Would also make it easier for multiple channels.


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/thammanna/osticket-slack/pull/11#issuecomment-356086426

**Comment by jeffnewbold** [comment]
Can't recall if I added the error that i'm getting re: "Slack: No Url for Curl" and the URL for osticket is truncated or otherwise not sending the full link.

**Pull request closed without merging**
